### ISSUE TITLE
1.2 installed and unable to load original firmware FW_RT3200_1.0.01.101415_prod

### ISSUE THREAD

**Issue by flowersrj** [dangowrt/owrt-ubi-installer#102]
When I try to degrade firmware from 1.2.00.273012 all I get after a minute or so is the message "the image file is incorrect".  

Any advice on how to get router to reload earlier firmware?   Computer connected to LAN 1 and Internet connected to a switch.

**Comment by mrkiko** [comment]
Hi!

so - it depens on the reasons why you are downgrading.

If you wanted to install OpenWrt via the UBI installer, then you may not actually need to downgrade, since support for signed images is available!! :)
Otherwise, you may try to hack things up to build a signed stock image if no u-boot modifications happened in the meantime from vendor side.

**Comment by flowersrj** [comment]
Just looking for a way to install Openwrt--Sent from my Android phone with GMX Mail. Please excuse my brevity.On 5/26/22, 1:48 PM mrkiko ***@***.***> wrote:

   
  Hi! 
  so - it depens on the reasons why you are downgrading. 
  If you wanted to install OpenWrt via the UBI installer, then you may not actually need to downgrade, since support for signed images is available!! :) Otherwise, you may try to hack things up to build a signed stock image if no u-boot modifications happened in the meantime from vendor side.

**Comment by flowersrj** [comment]
Where to I get the UBI version and instructions on installing it?

**Comment by flowersrj** [comment]
Danel,

 

Would you know if a GUI(Luci) is included ?

 

Thanks,

Riochi
 

 
 

Sent: Tuesday, May 31, 2022 at 9:26 AM

**Comment by dangowrt** [comment]
Yes, all images offered for download here come with LuCI preinstalled.

**Comment by mrkiko** [comment]
Closing this issue right now. Feel free to re-open it in case it's needed!

**Comment by org0000h** [comment]
> 

I think you should change the readme file . The  downgrading content part  of it  is confusing.

**Comment by flowersrj** [comment]
Daniel,Install worked great.  Could you provide a link where I could look for updates?Also, am I correct in assuming that backups taken from snapshots can't be restored?Thank you,Rich--Sent from my Android phone with GMX Mail. Please excuse my brevity.On 6/2/22, 7:20 PM Daniel Golle ***@***.***> wrote:

   
  Yes, all images offered for download here come with LuCI preinstalled.

**Comment by dangowrt** [comment]
> Any advice on how to get router to reload earlier firmware?

You can't (and that's intentional, complain at Belkin/Linksys).

You can, however, use the `_signed` version of the installer and install
OpenWrt **without having to downgrade to v1.0**.
