### ISSUE TITLE
stuck in  recovery (initramfs) mode

### ISSUE THREAD

**Issue by Tom-Neverwinter** [dangowrt/owrt-ubi-installer#104]
woke up and noticed wifi was down. found out that the device is stuck in recovery.

Rebooting [undervolt issue?] or attempting to overwrite ubi partition with installer or installer signed:

openwrt-22.03-snapshot-r19338-ae64d0624c-mediatek-mt7622-linksys_e8450-ubi-initramfs-recovery_signed.itb

openwrt-22.03-snapshot-r19338-ae64d0624c-mediatek-mt7622-linksys_e8450-ubi-squashfs-sysupgrade.itb

etc.

leads back to:

OpenWrt SNAPSHOT r17758-b118efa0d2

probably have to flash over console?

**Comment by dangowrt** [comment]
Please check if there is a crashlog in pstore:
```
ls /sys/fs/pstore
```
If so, investigate **and delete those files**, then the router will boot again to production firmware.

**NEVER** re-run the installer. This won't fix anything if you are already running OpenWrt at this point.

**Comment by Tom-Neverwinter** [comment]
`Please append a correct "root=" boot option; here are the avai[10;12H56337] 1f00             512 mtdblock0                                [11;15H43]  (driver?)                    [12;12H62875] 1f01             256 mtdblock1[13;16H9]  (driver?)                    [14;13H9401] 1f02             512 mtdblock2[15;16H5]  (driver?)                    [16;12H75933] 1f03             512 mtdblock3[17;16H6]  (driver?)                    [18;12H82463] 1f04            1024 mtdblock4[19;16H7]  (driver?)                    [20;13H8988] 1f05             128 mtdblock5[21;15H92]  (driver?)                    [22;12H95520] 1f06             128 mtdblock6[23;16H4]  (driver?)                    [23;1H[24;1H[K- dmesg-ramoops-0 [Readonly] 115/130 88%[23;1H[1;2H5>[    2.256866] UBI: auto-attach mtd10      [2;12H60284] ubi0: attaching mtd10 [3;11H317075] ubi0: scanning is finished[4;2H3>[    2.320831] ubi0 error: ubi_read_volume_table: the layout volume was not f[5;13H8108] ubi0 error: ubi_attach_mtd_dev: failed to attach mtd10, error [6;12H35269] UBI error: cannot attach mtd10                               [7;2H7>[    2.340441] VFS: Cannot open root device "(null)" or unknown-block(0,0): e[8;13H7955] Please append a correct "root=" boot option; here are the avai[9;12H56337] 1f00             512 mtdblock0                                [10;15H43]  (driver?)                    [11;12H62875] 1f01             256 mtdblock1[12;16H9]  (driver?)                    [13;13H9401] 1f02             512 mtdblock2[14;16H5]  (driver?)                    [15;12H75933] 1f03             512 mtdblock3[16;16H6]  (driver?)                    [17;12H82463] 1f04            1024 mtdblock4[18;16H7]  (driver?)                    [19;13H8988] 1f05             128 mtdblock5[20;15H92]  (driver?)                    [21;12H95520] 1f06             128 mtdblock6[22;16H4]  (driver?)                    [23;11H402050] 1f07             128 mtdblock7[23;1H[24;1H[K- dmesg-ramoops-0 [Readonly] 116/130 89%[23;1H[1;12H60284] ubi0: attaching mtd10 [2;11H317075] ubi0: scanning is finished[3;2H3>[    2.320831] ubi0 error: ubi_read_volume_table: the layout volume was not f[4;13H8108] ubi0 error: ubi_attach_mtd_dev: failed to attach mtd10, error [5;12H35269] UBI error: cannot attach mtd10                               [6;2H7>[    2.340441] VFS: Cannot open root device "(null)" or unknown-block(0,0): e[7;13H7955] Please append a correct "root=" boot option; here are the avai[8;12H56337] 1f00             512 mtdblock0                                [9;15H43]  (driver?)                    [10;12H62875] 1f01             256 mtdblock1[11;16H9]  (driver?)                    [12;13H9401] 1f02             512 mtdblock2[13;16H5]  (driver?)                    [14;12H75933] 1f03             512 mtdblock3[15;16H6]  (driver?)                    [16;12H82463] 1f04            1024 mtdblock4[17;16H7]  (driver?)                    [18;13H8988] 1f05             128 mtdblock5[19;15H92]  (driver?)                    [20;12H95520] 1f06             128 mtdblock6[21;16H4]  (driver?)                    [22;11H402050] 1f07             128 mtdblock7[23;16H4]  (driver?)                    [23;1H[24;1H[K- dmesg-ramoops-0 [Readonly] 117/130 90%[23;1H[1;11H317075] ubi0: scanning is finished[2;2H3>[    2.320831] ubi0 error: ubi_read_volume_table: the layout volume was not f[3;13H8108] ubi0 error: ubi_attach_mtd_dev: failed to attach mtd10, error [4;12H35269] UBI error: cannot attach mtd10                               [5;2H7>[    2.340441] VFS: Cannot open root device "(null)" or unknown-block(0,0): e[6;13H7955] Please append a correct "root=" boot option; here are the avai[7;12H56337] 1f00             512 mtdblock0                                [8;15H43]  (driver?)                    [9;12H62875] 1f01             256 mtdblock1[10;16H9]  (driver?)                    [11;13H9401] 1f02             512 mtdblock2[12;16H5]  (driver?)                    [13;12H75933] 1f03             512 mtdblock3[14;16H6]  (driver?)                    [15;12H82463] 1f04            1024 mtdblock4[16;16H7]  (driver?)                    [17;13H8988] 1f05             128 mtdblock5[18;15H92]  (driver?)                    [19;12H95520] 1f06             128 mtdblock6[20;16H4]  (driver?)                    [21;11H402050] 1f07             128 mtdblock7[22;16H4]  (driver?)                    [23;13H8575] 1f08           30720 mtdblock8[23;1H[24;1H[K- dmesg-ramoops-0 [Readonly] 118/130 90%[23;1H[1;2H3>[    2.320831] ubi0 error: ubi_read_volume_table: the layout volume was not f[2;13H8108] ubi0 error: ubi_attach_mtd_dev: failed to attach mtd10, error [3;12H35269] UBI error: cannot attach mtd10                               [4;2H7>[    2.340441] VFS: Cannot open root device "(null)" or unknown-block(0,0): e[5;13H7955] Please append a correct "root=" boot option; here are the avai[6;12H56337] 1f00             512 mtdblock0                                [7;15H43]  (driver?)                    [8;12H62875] 1f01             256 mtdblock1[9;16H9]  (driver?)                    [10;13H9401] 1f02             512 mtdblock2[11;16H5]  (driver?)                    [12;12H75933] 1f03             512 mtdblock3[13;16H6]  (driver?)                    [14;12H82463] 1f04            1024 mtdblock4[15;16H7]  (driver?)                    [16;13H8988] 1f05             128 mtdblock5[17;15H92]  (driver?)                    [18;12H95520] 1f06             128 mtdblock6[19;16H4]  (driver?)                    [20;11H402050] 1f07             128 mtdblock7[21;16H4]  (driver?)                    [22;13H8575] 1f08           30720 mtdblock8[23;16H8]  (driver?)                    [23;1H[24;1H[K- dmesg-ramoops-0 [Readonly] 119/130 91%[23;1H[1;13H8108] ubi0 error: ubi_attach_mtd_dev: failed to attach mtd10, error [2;12H35269] UBI error: cannot attach mtd10                               [3;2H7>[    2.340441] VFS: Cannot open root device "(null)" or unknown-block(0,0): e[4;13H7955] Please append a correct "root=" boot option; here are the avai[5;12H56337] 1f00             512 mtdblock0                                [6;15H43]  (driver?)                    [7;12H62875] 1f01             256 mtdblock1[8;16H9]  (driver?)                    [9;13H9401] 1f02             512 mtdblock2[10;16H5]  (driver?)                    [11;12H75933] 1f03             512 mtdblock3[12;16H6]  (driver?)                    [13;12H82463] 1f04            1024 mtdblock4[14;16H7]  (driver?)                    [15;13H8988] 1f05             128 mtdblock5[16;15H92]  (driver?)                    [17;12H95520] 1f06             128 mtdblock6[18;16H4]  (driver?)                    [19;11H402050] 1f07             128 mtdblock7[20;16H4]  (driver?)                    [21;13H8575] 1f08           30720 mtdblock8[22;16H8]  (driver?)                    [23;12H15106] 1f09           30720 mtdblock9[23;1H[24;1H[K- dmesg-ramoops-0 [Readonly] 120/130 92%[23;1H[1;12H35269] UBI error: cannot attach mtd10                               [2;2H7>[    2.340441] VFS: Cannot open root device "(null)" or unknown-block(0,0): e[3;13H7955] Please append a correct "root=" boot option; here are the avai[4;12H56337] 1f00             512 mtdblock0                                [5;15H43]  (driver?)                    [6;12H62875] 1f01             256 mtdblock1[7;16H9]  (driver?)                    [8;13H9401] 1f02             512 mtdblock2[9;16H5]  (driver?)                    [10;12H75933] 1f03             512 mtdblock3[11;16H6]  (driver?)                    [12;12H82463] 1f04            1024 mtdblock4[13;16H7]  (driver?)                    [14;13H8988] 1f05             128 mtdblock5[15;15H92]  (driver?)                    [16;12H95520] 1f06             128 mtdblock6[17;16H4]  (driver?)                    [18;11H402050] 1f07             128 mtdblock7[19;16H4]  (driver?)                    [20;13H8575] 1f08           30720 mtdblock8[21;16H8]  (driver?)                    [22;12H15106] 1f09           30720 mtdblock9[23;15H10]  (driver?)                    [23;1H[24;1H[K- dmesg-ramoops-0 [Readonly] 121/130 93%[23;1H[1;2H7>[    2.340441] VFS: Cannot open root device "(null)" or unknown-block(0,0): e[2;13H7955] Please append a correct "root=" boot option; here are the avai[3;12H56337] 1f00             512 mtdblock0                                [4;15H43]  (driver?)                    [5;12H62875] 1f01             256 mtdblock1[6;16H9]  (driver?)                    [7;13H9401] 1f02             512 mtdblock2[8;16H5]  (driver?)                    [9;12H75933] 1f03             512 mtdblock3[10;16H6]  (driver?)                    [11;12H82463] 1f04            1024 mtdblock4[12;16H7]  (driver?)                    [13;13H8988] 1f05             128 mtdblock5[14;15H92]  (driver?)                    [15;12H95520] 1f06             128 mtdblock6[16;16H4]  (driver?)                    [17;11H402050] 1f07             128 mtdblock7[18;16H4]  (driver?)                    [19;13H8575] 1f08           30720 mtdblock8[20;16H8]  (driver?)                    [21;12H15106] 1f09           30720 mtdblock9[22;15H10]  (driver?)                    [23;12H21636] 1f0a           25600 mtdblock10[23;1H[24;1H[K- dmesg-ramoops-0 [Readonly] 122/130 93%[23;1H[1;13H7955] Please append a correct "root=" boot option; here are the avai[2;12H56337] 1f00             512 mtdblock0                                [3;15H43]  (driver?)                    [4;12H62875] 1f01             256 mtdblock1[5;16H9]  (driver?)                    [6;13H9401] 1f02             512 mtdblock2[7;16H5]  (driver?)                    [8;12H75933] 1f03             512 mtdblock3[9;16H6]  (driver?)                    [10;12H82463] 1f04            1024 mtdblock4[11;16H7]  (driver?)                    [12;13H8988] 1f05             128 mtdblock5[13;15H92]  (driver?)                    [14;12H95520] 1f06             128 mtdblock6[15;16H4]  (driver?)                    [16;11H402050] 1f07             128 mtdblock7[17;16H4]  (driver?)                    [18;13H8575] 1f08           30720 mtdblock8[19;16H8]  (driver?)                    [20;12H15106] 1f09           30720 mtdblock9[21;15H10]  (driver?)                    [22;12H21636] 1f0a           25600 mtdblock10[23;15H40]  (driver?)                     [23;1H[24;1H[K- dmesg-ramoops-0 [Readonly] 123/130 94%[23;1H[1;12H56337] 1f00             512 mtdblock0                                [2;15H43]  (driver?)                    [3;12H62875] 1f01             256 mtdblock1[4;16H9]  (driver?)                    [5;13H9401] 1f02             512 mtdblock2[6;16H5]  (driver?)                    [7;12H75933] 1f03             512 mtdblock3[8;16H6]  (driver?)                    [9;12H82463] 1f04            1024 mtdblock4[10;16H7]  (driver?)                    [11;13H8988] 1f05             128 mtdblock5[12;15H92]  (driver?)                    [13;12H95520] 1f06             128 mtdblock6[14;16H4]  (driver?)                    [15;11H402050] 1f07             128 mtdblock7[16;16H4]  (driver?)                    [17;13H8575] 1f08           30720 mtdblock8[18;16H8]  (driver?)                    [19;12H15106] 1f09           30720 mtdblock9[20;15H10]  (driver?)                    [21;12H21636] 1f0a           25600 mtdblock10[22;15H40]  (driver?)                     [23;13H8249] 1f0b           20480 mtdblock11[23;1H[24;1H[K- dmesg-ramoops-0 [Readonly] 124/130 95%[23;1H[1;15H43]  (driver?)                    [2;12H62875] 1f01             256 mtdblock1[3;16H9]  (driver?)                    [4;13H9401] 1f02             512 mtdblock2[5;16H5]  (driver?)                    [6;12H75933] 1f03             512 mtdblock3[7;16H6]  (driver?)                    [8;12H82463] 1f04            1024 mtdblock4[9;16H7]  (driver?)                    [10;13H8988] 1f05             128 mtdblock5[11;15H92]  (driver?)                    [12;12H95520] 1f06             128 mtdblock6[13;16H4]  (driver?)                    [14;11H402050] 1f07             128 mtdblock7[15;16H4]  (driver?)                    [16;13H8575] 1f08           30720 mtdblock8[17;16H8]  (driver?)                    [18;12H15106] 1f09           30720 mtdblock9[19;15H10]  (driver?)                    [20;12H21636] 1f0a           25600 mtdblock10[21;15H40]  (driver?)                     [22;13H8249] 1f0b           20480 mtdblock11[23;15H53]  (driver?)                     [23;1H[24;1H[K- dmesg-ramoops-0 [Readonly] 125/130 96%[23;1H[1;12H62875] 1f01             256 mtdblock1[2;16H9]  (driver?)                    [3;13H9401] 1f02             512 mtdblock2[4;16H5]  (driver?)                    [5;12H75933] 1f03             512 mtdblock3[6;16H6]  (driver?)                    [7;12H82463] 1f04            1024 mtdblock4[8;16H7]  (driver?)                    [9;13H8988] 1f05             128 mtdblock5[10;15H92]  (driver?)                    [11;12H95520] 1f06             128 mtdblock6[12;16H4]  (driver?)                    [13;11H402050] 1f07             128 mtdblock7[14;16H4]  (driver?)                    [15;13H8575] 1f08           30720 mtdblock8[16;16H8]  (driver?)                    [17;12H15106] 1f09           30720 mtdblock9[18;15H10]  (driver?)                    [19;12H21636] 1f0a           25600 mtdblock10[20;15H40]  (driver?)                     [21;13H8249] 1f0b           20480 mtdblock11[22;15H53]  (driver?)                     [23;2H0>[    2.434866] Kernel panic - not syncing: VFS: Unable to mount root fs on un[23;1H[24;1H[K- dmesg-ramoops-0 [Readonly] 126/130 96%[23;1H[1;16H9]  (driver?)                    [2;13H9401] 1f02             512 mtdblock2[3;16H5]  (driver?)                    [4;12H75933] 1f03             512 mtdblock3[5;16H6]  (driver?)                    [6;12H82463] 1f04            1024 mtdblock4[7;16H7]  (driver?)                    [8;13H8988] 1f05             128 mtdblock5[9;15H92]  (driver?)                    [10;12H95520] 1f06             128 mtdblock6[11;16H4]  (driver?)                    [12;11H402050] 1f07             128 mtdblock7[13;16H4]  (driver?)                    [14;13H8575] 1f08           30720 mtdblock8[15;16H8]  (driver?)                    [16;12H15106] 1f09           30720 mtdblock9[17;15H10]  (driver?)                    [18;12H21636] 1f0a           25600 mtdblock10[19;15H40]  (driver?)                     [20;13H8249] 1f0b           20480 mtdblock11[21;15H53]  (driver?)                     [22;2H0>[    2.434866] Kernel panic - not syncing: VFS: Unable to mount root fs on un[23;2H2>[    2.443120] SMP: stopping secondary CPUs                                  [23;1H[24;1H[K- dmesg-ramoops-0 [Readonly] 127/130 97%[23;1H[1;13H9401] 1f02             512 mtdblock2[2;16H5]  (driver?)                    [3;12H75933] 1f03             512 mtdblock3[4;16H6]  (driver?)                    [5;12H82463] 1f04            1024 mtdblock4[6;16H7]  (driver?)                    [7;13H8988] 1f05             128 mtdblock5[8;15H92]  (driver?)                    [9;12H95520] 1f06             128 mtdblock6[10;16H4]  (driver?)                    [11;11H402050] 1f07             128 mtdblock7[12;16H4]  (driver?)                    [13;13H8575] 1f08           30720 mtdblock8[14;16H8]  (driver?)                    [15;12H15106] 1f09           30720 mtdblock9[16;15H10]  (driver?)                    [17;12H21636] 1f0a           25600 mtdblock10[18;15H40]  (driver?)                     [19;13H8249] 1f0b           20480 mtdblock11[20;15H53]  (driver?)                     [21;2H0>[    2.434866] Kernel panic - not syncing: VFS: Unable to mount root fs on un[22;2H2>[    2.443120] SMP: stopping secondary CPUs                                  [23;2H0>[    2.447035] Kernel Offset: disabled     [23;1H[24;1H[K- dmesg-ramoops-0 [Readonly] 128/130 98%[23;1H[1;16H5]  (driver?)                    [2;12H75933] 1f03             512 mtdblock3[3;16H6]  (driver?)                    [4;12H82463] 1f04            1024 mtdblock4[5;16H7]  (driver?)                    [6;13H8988] 1f05             128 mtdblock5[7;15H92]  (driver?)                    [8;12H95520] 1f06             128 mtdblock6[9;16H4]  (driver?)                    [10;11H402050] 1f07             128 mtdblock7[11;16H4]  (driver?)                    [12;13H8575] 1f08           30720 mtdblock8[13;16H8]  (driver?)                    [14;12H15106] 1f09           30720 mtdblock9[15;15H10]  (driver?)                    [16;12H21636] 1f0a           25600 mtdblock10[17;15H40]  (driver?)                     [18;13H8249] 1f0b           20480 mtdblock11[19;15H53]  (driver?)                     [20;2H0>[    2.434866] Kernel panic - not syncing: VFS: Unable to mount root fs on un[21;2H2>[    2.443120] SMP: stopping secondary CPUs                                  [22;2H0>[    2.447035] Kernel Offset: disabled     [23;12H50513] CPU features: 0x00003000,00000802[23;1H[24;1H[K- dmesg-ramoops-0 [Readonly] 129/130 99%[23;1H[1;12H75933] 1f03             512 mtdblock3[2;16H6]  (driver?)                    [3;12H82463] 1f04            1024 mtdblock4[4;16H7]  (driver?)                    [5;13H8988] 1f05             128 mtdblock5[6;15H92]  (driver?)                    [7;12H95520] 1f06             128 mtdblock6[8;16H4]  (driver?)                    [9;11H402050] 1f07             128 mtdblock7[10;16H4]  (driver?)                    [11;13H8575] 1f08           30720 mtdblock8[12;16H8]  (driver?)                    [13;12H15106] 1f09           30720 mtdblock9[14;15H10]  (driver?)                    [15;12H21636] 1f0a           25600 mtdblock10[16;15H40]  (driver?)                     [17;13H8249] 1f0b           20480 mtdblock11[18;15H53]  (driver?)                     [19;2H0>[    2.434866] Kernel panic - not syncing: VFS: Unable to mount root fs on un[20;2H2>[    2.443120] SMP: stopping secondary CPUs                                  [21;2H0>[    2.447035] Kernel Offset: disabled     [22;12H50513] CPU features: 0x00003000,00000802[23;13H4861] Memory Limit: none               [23;1H[24;1H[K- dmesg-ramoops-0 [Readonly] 130/130 100%[23;1H[23;1H[23;1H[23;1H[23;1H[23;1H[23;1H[23;1H[23;1H[23;1H[23;1H[23;1H[23;1H[23;1H[23;1H[23;1H[23;1H[23;1H[23;1H[23;1H[23;1H[23;1H[23;1H[23;1H[23;1H[24;1H[K:q[23;1H[23;1H[24;1H[K- dmesg-ramoops-0 [Readonly] 130/130 100%[23;1H[24;1H[K[?1049l]0;root@OpenWrt: /sys/fs/pstoreroot@OpenWrt:/sys/fs/pstore# exit`

**Comment by dangowrt** [comment]
This looks like you have flashed the non-UBI firmware despite already having converted the device to UBI layout.
MTD devices do **not** have a partition table (such as MBR or GPT), instead the partition layout is given with the device tree and part of the OS you flash. Hence, if you get to see too many MTD devices, that's because you have booted with a device tree which defines them (but, obviously, the right content is not in place).
Just make sure to flash the correct image (with `-ubi-` in it's name) and you'll be fine.

**Comment by Tom-Neverwinter** [comment]
flashing from "http://192.168.1.1/cgi-bin/luci/admin/system/flash" 

using: "openwrt-22.03-snapshot-r19338-ae64d0624c-mediatek-mt7622-linksys_e8450-ubi-squashfs-sysupgrade.itb"

still loads into recovery (initramfs) mode

**Comment by Tom-Neverwinter** [comment]
solved. issue is "I'm an idiot. "

**Comment by dangowrt** [comment]
Good to read that the issue has been resolved!
