### ISSUE TITLE
OpenWrt SNAPSHOT r18125-b764cb9e5b

### ISSUE THREAD

**Issue by freew01f** [dangowrt/owrt-ubi-installer#118]
my e8450 is running on OpenWrt SNAPSHOT r18125-b764cb9e5b
but I flash the new realease version 22
but it is only work in initramfs mode 
```
System running in recovery (initramfs) mode.
```
flash the openwrt-22.03.0-mediatek-mt7622-linksys_e8450-ubi-initramfs-recovery.itb
still initramfs mode on OpenWrt SNAPSHOT r18125-b764cb9e5b

flash the openwrt-mediatek-mt7622-linksys_e8450-ubi-squashfs-sysupgrade 
still initramfs mode on OpenWrt SNAPSHOT r18125-b764cb9e5b

how can i fix it

**Comment by dangowrt** [comment]
Either you have flashed a wrong file (only **`sysupgrade`** file will work, make sure it's the **`ubi`** variant) or there is a kernel crashlog in pstore to be taken care of:
```
ls /sys/fs/pstore/
cat /sys/fs/pstore/*
rm /sys/fs/pstore/*
reboot
```
Let me know what the output is and if that fixes your issue.

**Comment by freew01f** [comment]
restart  some times it is ok 
OMG
thanks
