### ISSUE TITLE
Link for Belkin FW is dead

### ISSUE THREAD

**Issue by 4r1-60ld** [dangowrt/owrt-ubi-installer#126]
Don't know if this is the correct place for it, but it appear the link for the downgrade Belkin RT 3200 is dead and I cannot find it.... 
Thank you.

EDIT: Unsure if i can use the Linksys FW for my Belkin that is arriving in the post tomorrow. Can anyone confirm that they an be used "interchangeably".

**Comment by mdr92** [comment]
I hit the same problem, here's the new link, just s3 instead of www, the firmware is probably interchangeable but the Linksus has more lights if that would make a difference.
https://s3.belkin.com/support/assets/belkin/firmware/FW_RT3200_1.0.01.101415_prod.img

**Comment by 4r1-60ld** [comment]
> I hit the same problem, here's the new link, just s3 instead of www, the firmware is probably interchangeable but the Linksys has more lights if that would make a difference.
> https://s3.belkin.com/support/assets/belkin/firmware/FW_RT3200_1.0.01.101415_prod.img

Thank you!
