### ISSUE TITLE
About upgrade and future maintenance

### ISSUE THREAD

**Issue by sommella** [dangowrt/owrt-ubi-installer#133]
Hi,
If I use UBI version provided here, when I will upgrade OpenWrt I will need the sysupgrade provided by you or to use the script to build my own, I cannot use the one available on OpenWrt repo, right?

For example there is https://downloads.openwrt.org/releases/22.03.3/targets/mediatek/mt7622/openwrt-22.03.3-mediatek-mt7622-linksys_e8450-squashfs-sysupgrade.bin that is 22.03.3 but your latest is 22.03.1.

Also, regarding future maintenance what does it happen if you decide to remove or stop maintain the project?

Thanks

**Comment by mrkiko** [comment]
Hi!!


On Wed, 25 Jan 2023, sommella wrote:

> Date: Wed, 25 Jan 2023 10:37:58
> From: sommella ***@***.***>
> Reply-To: dangowrt/owrt-ubi-installer
>     ***@***.***>
> To: dangowrt/owrt-ubi-installer ***@***.***>
> Cc: Subscribed ***@***.***>
> Subject: [dangowrt/owrt-ubi-installer] About upgrade and future maintenance
>     (Issue #133)
> 
> 
> Hi,
> If I use UBI version provided here, when I will upgrade OpenWrt I will need the sysupgrade provided by you or to use the script to build my own, I cannot use the one available on OpenWrt repo, right?

This repository contains the installer cod, which you need to run only once per device to perform the actual installation of the new bootloader, and change flash layout to UBI with all associated benefits.
> 
> For example there is https://downloads.openwrt.org/releases/22.03.3/targets/mediatek/mt7622/openwrt-22.03.3-mediatek-mt7622-linksys_e8450-squashfs-sysupgrade.bin that is 22.03.3 but your latest is 22.03.1.

Right, you should use the one made for the UBI layout and do sysupgrade normally.
For example: you may sysupgrade with this file
https://archive.openwrt.org/releases/22.03.2/targets/mediatek/mt7622/openwrt-22.03.2-mediatek-mt7622-linksys_e8450-ubi-squashfs-sysupgrade.itb

Or, if you would like to use the snapshot:
https://downloads.openwrt.org/snapshots/targets/mediatek/mt7622/openwrt-mediatek-mt7622-linksys_e8450-ubi-squashfs-sysupgrade.itb


> 
> Also, regarding future maintenance what does it happen if you decide to remove or stop maintain the project?

Can't speak for Daniel, but I don't think this project is going away soon, at least until the device becomes very obsolete.
But when you ran the installer once and your bootloader got replaced and flash layout changed, you can follow the normal OpenWrt release flow, no need to "come back" here.

> 
> Thanks

Thanks,

Enrico

**Comment by sommella** [comment]
Thanks!
