### ISSUE TITLE
build config and dts

### ISSUE THREAD

**Issue by yeezyio** [dangowrt/owrt-ubi-installer#178]
Can you share the build config and dts that you use to build u-boot?

**Comment by dangowrt** [comment]
It's stock OpenWrt.
U-Boot: https://github.com/openwrt/openwrt/blob/main/package/boot/uboot-mediatek/patches/410-add-linksys-e8450.patch
DTS: https://github.com/openwrt/openwrt/blob/main/target/linux/mediatek/dts/mt7622-linksys-e8450-ubi.dts

The installer script modifies the DT slightly to prevent UBI-auto-attach (by renaming `ubi` to `ibu`) and make allow write access to all MTD volumes.
