### ISSUE TITLE
I need help with some issues. My device light is off.

### ISSUE THREAD

**Issue by wangpengju00** [dangowrt/owrt-ubi-installer#186]
My device has switched to the UBI layout, but I installed a self-built system image before (the recovery on this page), and then I mistakenly updated the openwrt-mediatek-mt7622-linksys_e8450-ubi-squashfs-sysupgrade.itb (1.12) on this page under the sysupgrade page (only installed this), and now the device indicator light is not on, so I checked ttl output, it says "BL2: Failed to load image id 3" just like this: https://forum.openwrt.org/t/need-help-with-a-bricked-linksys-e8450/144836, I don't know what went wrong, and how I should solve the problem
![2bb3069a060627fa97c2f902eee5b47a311a6f2a](https://github.com/dangowrt/owrt-ubi-installer/assets/48021677/509a9510-cebf-4dc9-9e0c-0991ee773edb)

**Comment by wangpengju00** [comment]
![1718214467610](https://github.com/dangowrt/owrt-ubi-installer/assets/48021677/dfb05417-9838-47cc-b5f3-755207494654)
![1718214467604](https://github.com/dangowrt/owrt-ubi-installer/assets/48021677/d8370997-f48a-4d6b-a8a4-10e767666f2d)
I only have one such device that can connect to the e8450 and display this data, can I use it to solve my problem?

**Comment by dangowrt** [comment]
Yes, this adapter should work. Connect only GND to GND, TX to RX and RX to TX.

**Comment by wangpengju00** [comment]
OK, but after I use this adapter to connect to the motherboard, it only displays the following content, and there is no operable part. How can I use this adapter to solve my problem? Thank you.

F0: 102B 0000
F6: 0000 0000
V0: 0000 0000 [0001]
00: 0000 0000
BP: 0400 0041 [0000]
G0: 1190 0000
T0: 0000 02AF [000F]
Jump to BL

NOTICE:  BL2: v2.4(release):OpenWrt v2021-05-08-d2c75b21-3 (mt7622-snand-1ddr)
NOTICE:  BL2: Built : 02:55:34, Sep  3 2022
NOTICE:  SPI-NAND: FM35Q1GA (128MB)
ERROR:   BL2: Failed to load image id 3 (-2)

**Comment by wangpengju00** [comment]
> Yes, this adapter should work. Connect only GND to GND, TX to RX and RX to TX.


OK, but after I use this adapter to connect to the motherboard, it only displays the following content, and there is no operable part. How can I use this adapter to solve my problem? Thank you.

F0: 102B 0000
F6: 0000 0000
V0: 0000 0000 [0001]
00: 0000 0000
BP: 0400 0041 [0000]
G0: 1190 0000
T0: 0000 02AF [000F]
Jump to BL

NOTICE: BL2: v2.4(release):OpenWrt v2021-05-08-d2c75b21-3 (mt7622-snand-1ddr)
NOTICE: BL2: Built : 02:55:34, Sep 3 2022
NOTICE: SPI-NAND: FM35Q1GA (128MB)
ERROR: BL2: Failed to load image id 3 (-2)

**Comment by wangpengju00** [comment]
This is the latest content displayed on my computer
![屏幕截图 2024-06-13 085508](https://github.com/dangowrt/owrt-ubi-installer/assets/48021677/e5deee70-602b-44fb-88b5-311193dbbecc)

**Comment by mrkiko** [comment]
On Wed, Jun 12, 2024 at 06:00:58PM -0700, wangpengju00 wrote:
> > Yes, this adapter should work. Connect only GND to GND, TX to RX and RX to TX.
> 
> OK, but after I use this adapter to connect to the motherboard, it only displays the following content, and there is no operable part. How can I use this adapter to solve my problem? Thank you.
> ![屏幕截图 2024-06-13 085508](https://github.com/dangowrt/owrt-ubi-installer/assets/48021677/a53e7f17-637a-4d50-9168-e913c0940b4c)
> 

Hi!

you will probably need
mtk_uartboot
search for it around in the openwrt forum and/or maybe the issues (even closed) of this repo.

**Comment by user8446** [comment]
Instructions to recover from the "OpenWrt Kiss of Death":

https://openwrt.org/toh/linksys/e8450#recovery_from_openwrt_kiss_of_death_okd
