### ISSUE TITLE
Missing instructions on how to upgrade TF-A/U-Boot to newer versions.

### ISSUE THREAD

**Issue by hrw** [dangowrt/owrt-ubi-installer#188]
I installed OpenWRT on E8450 in 2021. Used installer 0.5.3 (looking at TF-A 2.4 + U-Boot 2021.04 versions).

Device refuses to upgrade from 23.05.2 -> 23.05.3 and I started to wonder do I need to update bootloaders.

But your docs say "vendor FW -> OpenWRT" and vice-versa only.

Please add instructions on how to update bootloaders.

**Comment by justinkb** [comment]
I guess we just need to revert to original firmware and then install openwrt again

**Comment by hrw** [comment]
There should be also a way to do it without going to vendor firmware.

**Comment by justinkb** [comment]
Yes, I've just found it. You can find the details in the comments on the
commit from the dev branch that introduces the fip on ubi change for this
device

**Comment by hrw** [comment]
You found it then please post a link to change.

Nit everyone has a time or skills to find such data. And there will be users needing it

**Comment by justinkb** [comment]
https://github.com/openwrt/openwrt/commit/6aec3c7b5bf5e5a999a12121dfa71963afb6f003#commitcomment-139151946

https://github.com/openwrt/openwrt/commit/6aec3c7b5bf5e5a999a12121dfa71963afb6f003#commitcomment-139240065

**Comment by hrw** [comment]
Followed instructions, OpenWRT 24.10-rc1 works on my device.

Thanks!
