### ISSUE TITLE
Deletion of bl2-for-mtk_uartboot.bin

### ISSUE THREAD

**Issue by petrij98** [dangowrt/owrt-ubi-installer#190]
I can no longer recover my bricked Belkin RT3200 because all instances of this essential file for mtk_uartboot have been removed. Using this file is critical in the official recovery guide on OpenWRT's website.

**Comment by dangowrt** [comment]
Images for `mtk_uartboot` are now built for all newer MediaTek platforms in the regular OpenWrt build system. I've opened a PR https://github.com/openwrt/openwrt/pull/16178 which suggests to do the same also for MT7622.

**Comment by jaws35smith** [comment]
@dangowrt so does that mean the recovery procedures are now incorrect? @petrij98 I would recommend using wayback machine to grab the .bin in the mean time until the recovery procedures are updated.

**Comment by dangowrt** [comment]
You can grab the file here: https://downloads.openwrt.org/snapshots/targets/mediatek/mt7622/mt7622-ram-1ddr-bl2.bin
Instructions will need to be updated.
