### ISSUE TITLE
5G missing

### ISSUE THREAD

**Issue by oooooolr** [dangowrt/owrt-ubi-installer#206]
flashed openwrt-mediatek-mt7622-linksys_e8450-ubi-initramfs-recovery-installer_signed.itb and openwrt-23.05.5-mediatek-mt7622-linksys_e8450-ubi-squashfs-sysupgrade.itb 5G missing

tried to install mt7915
`opkg install kmod-mt7915-firmware
Unknown package 'kmod-mt7915-firmware'.
Collected errors:
 opkg_install_cmd: Cannot install package kmod-mt7915-firmware.`
 
tried to download mt7915_eepom.bin and put inside the router:
`root@OpenWrt:~# dmesg | grep mt7915

[    8.214920] mt7915e 0000:01:00.0: assign IRQ: got 150
[    8.225117] mt7915e 0000:01:00.0: enabling device (0000 -> 0002)
[    8.231230] mt7915e 0000:01:00.0: enabling bus mastering
[    8.411264] mt7915e 0000:01:00.0: HW/SW Version: 0x8a108a10, Build Time: 20211222184017a
[    8.541644] mt7915e 0000:01:00.0: WM Firmware Version: ____000000, Build Time: 20211222184052
[    8.608517] mt7915e 0000:01:00.0: WA Firmware Version: DEV_000000, Build Time: 20211222184111
[    8.741624] mt7915e 0000:01:00.0: eeprom load fail, use default bin
[    8.747993] mt7915e 0000:01:00.0: Direct firmware load for mediatek/mt7915_eeprom.bin failed with error -2
[    8.757645] mt7915e 0000:01:00.0: Falling back to sysfs fallback for: mediatek/mt7915_eeprom.bin
[    8.773151] mt7915e: probe of 0000:01:00.0 failed with error -12`

tried to reflash the installer.itb and sysupgrade.itb 
tried to install lower version installer.itb and sysupgrade.itb 

all failed

**Comment by frycss** [comment]
Already reported here #198

I'm experiencing the same issue. I'm trying to restore the vendor firmware to start again but I'm encountering this error:

```
# ubidetach -d 0
ubidetach: error!: cannot remove ubi0
           error 16 (Resource busy)
```
