### ISSUE TITLE
every 2nd day wifi connection drops, restarting router makes it work again

### ISSUE THREAD

**Issue by pinkworld123** [dangowrt/owrt-ubi-installer#81]
hello,

there is a issue every 2nd day wifi connection drops, restarting router makes it work again.

Please fix this. I have tried to analyze this from last 3 weeks, and this happens every 2nd day i need to restart the router to make wifi connection work again without drop in connection. 

Thanks

**Comment by mrkiko** [comment]
Hi! This project aims to create an installer that allows you to convert your device to use a modern and very nice bootchain while allowing the use of UBI under Linux.
This allows for better usage of the flash chip and prolonged lifetime of the device.

The problem you are encountering does not seem related to these aspects, but to different components on the system.
I would recommend you discuss this issue in OpenWRt forum or GitHub issue tracker, posting logs and/or being more specific about your issue (e.g.: reporting if the problem happens on 5GHZ MT7915* or 2.4GHZ MT7615 interfaces).

Thanks!
