### ISSUE TITLE
kernel 5.10.111-xxx dependency for both Wireguard and OpenVPN server

### ISSUE THREAD

**Issue by MrPaulLiu** [dangowrt/owrt-ubi-installer#94]
I am hoping to install either OpenVPN or Wireguard server on my Belkin but am running into a kernel incompatibility issue. Is there a workaround or will there be a build soon that is compatible of either VPN servers?

Thank you in advance.

**Comment by dangowrt** [comment]
Please update to the official release-candidate first, that will also allow you to install additional kernel modules
https://downloads.openwrt.org/releases/22.03.0-rc1/targets/mediatek/mt7622/openwrt-22.03.0-rc1-mediatek-mt7622-linksys_e8450-ubi-squashfs-sysupgrade.itb
