### ISSUE TITLE
Good idea to update to latest?

### ISSUE THREAD

**Issue by msilletti** [dangowrt/owrt-ubi-installer#95]
Hi. I flashed v0.6.1 or v0.6.2 a while ago but see that v0.6.4 is out now. I am running the latest snapshot through just systemupdate but want to know if flashing v0.6.4 then updating to the latest snapshot is a good idea. Newer bootloader? Maybe something else too?

**Comment by dangowrt** [comment]
There haven't been any significant changes which would make it worth the risk of replacing the bootloader another time, just keep going with the official sysupgrade images (22.03.0-rc1, 22.03-SNAPSHOT or snapshots).
