### ISSUE TITLE
Fresh install on a Linksys E8450 settings do not persist after reboot

### ISSUE THREAD

**Issue by DimitryRakhlei** [dangowrt/owrt-ubi-installer#96]
Install seemed to work with no issues but every time I reboot the router it resets most settings except for the password (it still complains about password being unchanged). Is there a simple solution that I am missing in the docs? I have mtd0-3 backed up on my desktop.

**Comment by dangowrt** [comment]
Does the router indicate to be in `initramfs`/recovery mode? (warning in LuCI, `ubus call system board` via SSH shows `initramfs` as filesystem)

If you, did you follow through with the manual including the final step to flash the `sysupgrade` image when already running OpenWrt after initially flashing the `installer` image from stock firmware?

If you did flash the `sysupgrade` image it can be that something crashes and a log of that crash can then be found in `/sys/fs/pstore`. To check, connect via SSH and try `cat /sys/fs/pstore/*`. If that shows a crashlog, share it and delete the files in pstore, so the router resumes to reboot into the production image.

**Comment by abdoahmed79** [comment]
Facing the same issue with RT3200,

**Comment by DimitryRakhlei** [comment]
Solved it by flashing the sysupgrade image again. It must have not succeeded the first time.
