### ISSUE TITLE
attended sysupgrade not visible in Release v0.6.4

### ISSUE THREAD

**Issue by pinkworld123** [dangowrt/owrt-ubi-installer#98]
Hello, 

I have attached screenshot of flash on Belkin RT3200, Release v0.6.4 firmware. Problem is I can not see in webUI and also not in Terminal command for attended sysupgrade. When I have flashed with older version of firmware v0.6.2 firmware, I can see it and update it. 

<img width="151" alt="Screenshot 2022-05-09 at 04 57 52" src="https://user-images.githubusercontent.com/100469885/167333481-d21d1173-4235-4b0a-97a6-f2a5a4ea6031.png">
<img width="1026" alt="Screenshot 2022-05-09 at 04 58 07" src="https://user-images.githubusercontent.com/100469885/167333510-a5719848-d097-4a7c-ad6e-84e3a74e22d5.png">
 
Can you please tell me how to enable attended sysupgrade for Release v0.6.4. Thanks

**Comment by dangowrt** [comment]
Attended sysupgrade is not part of the official release, and since v0.6.4 instead of building a custom sysupgrade image, the official release-candidate image is used instead.

You can install the atteneded sysupgrade features using 
```
opkg update
opkg install luci-app-attendedsysupgrade auc
```

**Comment by pinkworld123** [comment]
Thanks
